### ISSUE TITLE
Request: ensure-labels-for-sections should modify files

### ISSUE THREAD

**Issue by Berk-Tosun** [jonasbb/pre-commit-latex-hooks#76]
Basically the title. ensure-labels-for-sections is a good hook; but printing warnings to the console does not really automate it.

Best,
Berk

**Comment by jonasbb** [comment]
Hi, thanks for the idea. That sounds reasonable. One difficult I see is that inserting a label might not exactly be what you want.
There might already be label, but with the wrong text. In that case you might rather want to update that label and all uses of that label, instead of only adding a second label. Doing a proper find and replace without errors seems difficult to impossible.
Another problem I see is that adding a new label can also introduce conflicts with existing ones, for example, if you have very generic titles like "evaluation". Worse, the conflicting existing label might not even be in the same file. Finding such conflicts would require updating the hook to process all files at once.

I'm not opposed to update the hook logic but first I would like to get some feedback on those points.

**Comment by Berk-Tosun** [comment]
Hello,

Regarding your points:
* If there is an existing label, I think it is best to not modify it. We should mark that section as ok. Then, we do not need to worry about find and replace.
* Second problem, especially checking among different files, sounds tricky with pre-commit. A solution that comes to my mind is to save existing labels in some file such as `.ensure-labels` and use that file for conflict checks. While adding the hook for the first time, the user must run it over all files and generate a complete `.ensure-labels`. After that, checking against only staged files should be sufficient, no?

**Comment by jonasbb** [comment]
> * If there is an existing label, I think it is best to not modify it. We should mark that section as ok. Then, we do not need to worry about find and replace.

This sounds to me like you want a different hook. It sounds to me like you do not actually care what exactly the label is, only that each section has a label. Part of the reason for the hook is that the label is always a slug of the section. What I ran into multiple times and found confusing is a label which has nothing in common with the section. Usually, that happened because they get created in sync, somebody renames the section but doesn't update the label. Now if you see a `\cref{old-label}` you have no idea which section it is.

So the hook could only insert a new label directly under the `\section` with the correct slug, but would leave all existing labels untouched.

> Second problem, especially checking among different files, sounds tricky with pre-commit. A solution that comes to my mind is to save existing labels in some file such as `.ensure-labels` and use that file for conflict checks. While adding the hook for the first time, the user must run it over all files and generate a complete `.ensure-labels`. After that, checking against only staged files should be sufficient, no?

Checking all files at once is not much of a problem, see the hook configuration options [`pass_filenames`](https://pre-commit.com/#hooks-pass_filenames) and [`require_serial`](https://pre-commit.com/#hooks-require_serial). There is the `unique-labels` hook, so maybe creating duplicate labels is fine.

**Comment by Berk-Tosun** [comment]
> Part of the reason for the hook is that the label is always a slug of the section. What I ran into multiple times and found confusing is a label which has nothing in common with the section.

That is a good point. The label must definitely reflect section name. I also think the full name tends to get long, so I prefer shorter names in section labels; that is why I was thinking we could have a more relaxed rule. Anyway, that is not critical and can be discussed later.

I think making sure each section has a label as its slug would definitely help. However, it must be a complete solution to actually help the user: the existing labels must be updated as well.
